INSERT INTO cursovaya.age_limits (id, year) VALUES (1, 0);
INSERT INTO cursovaya.age_limits (id, year) VALUES (2, 6);
INSERT INTO cursovaya.age_limits (id, year) VALUES (3, 12);
INSERT INTO cursovaya.genres (id, name, imagesg_id) VALUES (1, 'Аркада', 1);
INSERT INTO cursovaya.genres (id, name, imagesg_id) VALUES (2, 'Экшон', 2);
INSERT INTO cursovaya.genres (id, name, imagesg_id) VALUES (3, 'Приключения', 3);
INSERT INTO cursovaya.genres (id, name, imagesg_id) VALUES (4, 'Файтинг', 4);
INSERT INTO cursovaya.genres (id, name, imagesg_id) VALUES (5, 'Стратегии', 5);
INSERT INTO cursovaya.languages (id, name) VALUES (4, 'Japanese');
INSERT INTO cursovaya.languages (id, name) VALUES (1, 'Russian');
INSERT INTO cursovaya.languages (id, name) VALUES (3, 'Chinese');
INSERT INTO cursovaya.languages (id, name) VALUES (2, 'Huinglish');
INSERT INTO cursovaya.publishers (id, name) VALUES (1, 'EA');
INSERT INTO cursovaya.publishers (id, name) VALUES (2, 'Wargaming');
INSERT INTO cursovaya.publishers (id, name) VALUES (3, 'Blizard');
INSERT INTO cursovaya.products (id,idd, description, full_price, one_day_price, quantity, title, year_of_issue, age_limits_id, genres_id, imagesp_id, languages_id, platforms_id, publishers_id) VALUES (5,5, '3232323', 2, 1, 22, 'Igorkik', 23, 2, 2, 5, 3, 5, 1);
INSERT INTO cursovaya.products (id,idd, description, full_price, one_day_price, quantity, title, year_of_issue, age_limits_id, genres_id, imagesp_id, languages_id, platforms_id, publishers_id) VALUES (4,4, 'Вот тут вот очень много описания для теста влазит ли всё в нужный размер. Так вот и так...Вот тут вот очень много описания для теста влазит ли всё в нужный размер. Так вот и так...', 343, 12, 223, 'Spider man', 2000, 3, 2, 4, 3, 6, 3);